[[assignments]]
name = "ict_liquidity_sweep_ny_session_strategy"
symbol = "MNQ"
unit = "Minute"
interval = 1
barsback = 10
session_template = "Default"
setup = "ny_ifvg_liquidity_sweep"
entry = "retracement"
trade_window_start = "09:30"
trade_window_end = "11:30"
max_num_of_trades = 2