[[assignments]]
name = "ict_liquidity_sweep_ny_session_strategy"
symbol = "MNQ"
unit = "Minute"
interval = 1
session_template = "USEQ24Hour"
setup = "ny_ifvg_liquidity_sweep"
entry = "retracement"
trade_window_start = "13:30"
trade_window_end = "15:30"
max_num_of_trades = 2